export const DATA = [
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },

  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
  {
    imageUrl: require('./assets/light.jpg'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'LIGHT',
  },
  {
    imageUrl: require('./assets/dark.avif'),
    title: 'Title Text',
    body: 'A very long body text aka description',
    theme: 'DARK',
  },
];
